// <auto-generated />
namespace MartinsExquizite.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class changedCategoryid : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(changedCategoryid));
        
        string IMigrationMetadata.Id
        {
            get { return "201911021250445_changedCategoryid"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
